image: golang:alpine

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

.schedule-only:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - test
  - build
  - run
  - deploy

compile:
  stage: build
  script:
    - go build ./cmd/scraper
    - go build ./cmd/generate-web
  extends: .go-cache
  artifacts:
    paths:
      - ./scraper
      - ./generate-web

scrape:
  stage: run
  needs:
    - job: compile
  extends: .schedule-only
  script:
    - ./scraper -overwrite -dir ./data -threads 8
    - |
          if [ ! -z "$(git status --porcelain=v1 -- data 2>/dev/null)" ]; then
            # git config user.name "Scraper"
            # git config user.email "actions@users.noreply.github.com"
            # git add -A data
            # git commit -m "Latest data"
            # git push
            echo "Would have pushed data files"
          fi
  cache:
    paths:
      - ./cache
  artifacts:
    paths:
      - ./data

pages:
  stage: deploy
  needs:
    - job: compile
  script:
    - ./generate-web -data-dir ./data -output-dir ./public -path-prefix /ebucks-dealz
    - |
        if [ ! -z "$(git status --porcelain=v1 -- docs 2>/dev/null)" ]; then
          # git config user.name "Scraper"
          # git config user.email "actions@users.noreply.github.com"
          # git add -A docs
          # git commit -m "Latest web"
          # git push
          echo "Would have pushed web files"
        fi
  artifacts:
    paths:
      - ./public
