name: Scrape Latest eBucks Deals

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      - name: Build
        run: go build ./cmd/scraper

      - name: Cache scraper cache files
        uses: actions/cache@v2
        with:
          path: ./cache
          key: ebucks-colly-cache

      - name: Scrape
        run: ./scraper -overwrite -dir ./data -cache ./cache -threads 8

      - name: Commit and push any data changes
        run: |-
          git config user.name "Scraper"
          git config user.email "actions@users.noreply.github.com"
          git add -A data
          git commit -m "Latest data"
          git push
